# Do not change any values in this file
server:
  port: ${PORT:8080}

spring:
  datasource:
    hikari:
      maxLifetime: "1800000"
      connectionTimeout: "30000"
      idleTimeout: "600000"
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    url: ${MYSQL_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-circular-references: true
  profiles:
    default: "local"

ftp:
  server: ${FTP_STORAGE_URL}
  port: ${FTP_STORAGE_PORT}
  environment: ${FTP_STORAGE_ENVIRONMENT}
  username: ${FTP_STORAGE_USERNAME}
  password: ${FTP_STORAGE_PASSWORD}

security:
  allowed:
    domains: ${ALLOWED_DOMAINS}

logging:
  level:
    "[org.springframework]": OFF
    "[org.apache]": OFF

info:
  name: First Baptist Church Lagrange REST Api
  license:
    type: MIT License
    url: https://github.com/fbl-church/fbl-church-microservice/blob/master/LICENSE
  version: Snapshot
  contact:
    name: Sam Butler
    email: sambutler1017@icloud.com
    url: https://github.com/fbl-church/fbl-church-microservice
  description: Restful API's for managing first baptist church.
