# Template for setting configurations for local development
server:
  port: 8000

spring:
  datasource:
    username:
    password:
    url:

security:
  allowed:
    domains: "*"
  signing-key: "local-key"

ftp:
  server:
  port:
  environment: DEV
  username:
  password:
