# Template for setting configurations for local development
server:
  port: 8000

spring:
  datasource:
    username:
    password:
    url: jdbc:mysql://databasePI.ddnsfree.com:3306/fbl_church_DEV

security:
  allowed:
    domains: "*"
  signing-key: "local-key"
