# Do not change any values in this file
server:
  port: ${PORT:8080}

spring:
  datasource:
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    url: ${MYSQL_URL}

ftp:
  server: ${FTP_STORAGE_URL}
  port: ${FTP_STORAGE_PORT}
  environment: ${FTP_STORAGE_ENVIRONMENT}
  username: ${FTP_STORAGE_USERNAME}
  password: ${FTP_STORAGE_PASSWORD}

jwt:
  secret: ${JWT_SIGNING_KEY}
email:
  sendgrid-key: ${SENDGRID_API_KEY}
