# Workflow will build the fbl-church-microservice application on push to the branch and pull request for the branch.

name: FBL Church API Build

on:
  push:
    branches:
      - "**"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: FBL Church Microservice Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "adopt"
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1.0.6
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Run Build
        env:
          APP_ENVIRONMENT: ${{ secrets.APP_ENVIRONMENT }}
          MYSQL_TEST_USERNAME: ${{ secrets.MYSQL_TEST_USERNAME }}
          MYSQL_TEST_PASSWORD: ${{ secrets.MYSQL_TEST_PASSWORD }}
          MYSQL_TEST_URL: ${{ secrets.MYSQL_TEST_URL }}
          JWT_SIGNING_KEY: ${{ secrets.JWT_SIGNING_KEY }}
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          FTP_TEST_STORAGE_URL: ${{ secrets.FTP_TEST_STORAGE_URL }}
          FTP_TEST_STORAGE_PORT: ${{ secrets.FTP_TEST_STORAGE_PORT }}
          FTP_TEST_STORAGE_ENVIRONMENT: ${{ secrets.FTP_TEST_STORAGE_ENVIRONMENT }}
          FTP_TEST_STORAGE_USERNAME: ${{ secrets.FTP_TEST_STORAGE_USERNAME }}
          FTP_TEST_STORAGE_PASSWORD: ${{ secrets.FTP_TEST_STORAGE_PASSWORD }}
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: build -i
